Repository BackJinSa/zangBu_Back, pull requests merged in 2025-08, with the labels that each got.

#192 Feature/주민등록 진위확인 api 설계 및 rsa 암호화 구현
  src/main/java/bjs/zangbu/codef/encryption/RSAEncryption.java
  src/main/java/bjs/zangbu/codef/service/CodefTwoFactorService.java
  src/main/java/bjs/zangbu/codef/service/CodefTwoFactorServiceImpl.java
  src/main/java/bjs/zangbu/global/config/RootConfig.java
  src/main/java/bjs/zangbu/security/account/controller/AuthController.java
  src/main/java/bjs/zangbu/security/account/dto/request/AuthRequest.java
  src/main/java/bjs/zangbu/security/account/service/AuthService.java
  src/main/java/bjs/zangbu/security/account/service/AuthServiceImpl.java
Labels: ⭐ feat, 🍍 경환

#194 fix : s3 로직 삭제
  src/main/java/bjs/zangbu/deal/S3/S3Config.java
  src/main/java/bjs/zangbu/deal/S3/S3Uploader.java
  src/main/java/bjs/zangbu/deal/service/ContractServiceImpl.java
Labels: ♻️ refactor, 🍍 경환

#196 refactor: config 파일 위치 변경
  src/main/java/bjs/zangbu/global/config/RestConfig.java
  src/main/java/bjs/zangbu/map/service/MapServiceImpl.java
  src/main/java/bjs/zangbu/payment/config/RestConfig.java
Labels: ♻️ refactor, 🍾영오

#198 Feat/#6
  src/main/java/bjs/zangbu/fcm/controller/FcmController.java
  src/main/java/bjs/zangbu/fcm/dto/request/FcmRequest.java
  src/main/java/bjs/zangbu/fcm/mapper/FcmMapper.java
  src/main/java/bjs/zangbu/fcm/service/FcmServiceImpl.java
  src/main/java/bjs/zangbu/global/config/RootConfig.java
  src/main/java/bjs/zangbu/notification/controller/NotificationController.java
  src/main/java/bjs/zangbu/notification/dto/response/NotificationResponse.java
  src/main/java/bjs/zangbu/notification/service/NotificationServiceImpl.java
  src/main/resources/bjs/zangbu/fcm/mapper/FcmMapper.xml
  src/main/resources/bjs/zangbu/notification/mapper/NotificationMapper.xml
  src/test/java/bjs/zangbu/notification/mapper/NotificationMapperTest.java
Labels: ♻️ refactor, ⭐ feat, ⚽ 경민

#202 fix : 오류 픽스
  src/main/java/bjs/zangbu/codef/encryption/RSAEncryption.java
  src/main/java/bjs/zangbu/global/config/RootConfig.java
  src/main/java/bjs/zangbu/global/config/ServletConfig.java
  src/main/java/bjs/zangbu/ncp/auth/Holder.java
  src/main/java/bjs/zangbu/security/account/service/AuthServiceImpl.java
  src/main/java/bjs/zangbu/security/config/SecurityConfig.java
  src/main/java/bjs/zangbu/security/config/SecurityInitializer.java
  src/main/java/bjs/zangbu/security/filter/JwtUsernamePasswordAuthenticationFilter.java
  src/main/resources/bjs/zangbu/payment/mapper/PaymentMapper.xml
  src/main/resources/bjs/zangbu/review/mapper/ReviewMapper.xml
Labels: ♻️ refactor, 🍍 경환

#207 chore: 다운 그레이드 및 로컬 실행 테스트
  build.gradle
  erl_crash.dump
  src/main/java/bjs/zangbu/addressChange/controller/AddressChangeController.java
  src/main/java/bjs/zangbu/building/controller/BuildingController.java
  src/main/java/bjs/zangbu/building/controller/MainController.java
  src/main/java/bjs/zangbu/building/dto/request/BuildingRequest.java
  src/main/java/bjs/zangbu/building/dto/response/BuildingResponse.java
  src/main/java/bjs/zangbu/chat/config/JwtHandshakeInterceptor.java
  src/main/java/bjs/zangbu/chat/controller/ChatController.java
  src/main/java/bjs/zangbu/chat/dto/request/ChatRequest.java
  src/main/java/bjs/zangbu/chat/dto/response/ChatResponse.java
  src/main/java/bjs/zangbu/codef/controller/CodefController.java
  src/main/java/bjs/zangbu/codef/dto/request/CodefRequest.java
  src/main/java/bjs/zangbu/codef/dto/response/CodefResponse.java
  src/main/java/bjs/zangbu/codef/encryption/CodefEncryption.java
  src/main/java/bjs/zangbu/codef/encryption/RSAEncryption.java
  src/main/java/bjs/zangbu/codef/service/CodefServiceImpl.java
  src/main/java/bjs/zangbu/codef/service/CodefTwoFactorServiceImpl.java
  src/main/java/bjs/zangbu/deal/controller/DealController.java
  src/main/java/bjs/zangbu/deal/dto/request/DealRequest.java
  src/main/java/bjs/zangbu/deal/dto/response/DealResponse.java
  src/main/java/bjs/zangbu/deal/dto/response/DealWaitingListResponse.java
  src/main/java/bjs/zangbu/deal/vo/DealEnum.java
  src/main/java/bjs/zangbu/documentReport/dto/request/DocumentReportRequest.java
  src/main/java/bjs/zangbu/documentReport/dto/response/DocumentReportResponse.java
  src/main/java/bjs/zangbu/fcm/controller/FcmController.java
  src/main/java/bjs/zangbu/fcm/dto/request/FcmRequest.java
  src/main/java/bjs/zangbu/global/config/RootConfig.java
  src/main/java/bjs/zangbu/global/config/ServletConfig.java
  src/main/java/bjs/zangbu/global/config/SwaggerConfig.java
  src/main/java/bjs/zangbu/global/config/WebConfig.java
  src/main/java/bjs/zangbu/global/exception/GlobalExceptionHandler.java
  src/main/java/bjs/zangbu/member/controller/MemberController.java
  src/main/java/bjs/zangbu/member/dto/request/MemberRequest.java
  src/main/java/bjs/zangbu/member/dto/response/MemberResponse.java
  src/main/java/bjs/zangbu/ncp/auth/Holder.java
  src/main/java/bjs/zangbu/notification/controller/NotificationController.java
  src/main/java/bjs/zangbu/notification/dto/response/NotificationResponse.java
  src/main/java/bjs/zangbu/security/account/controller/AuthController.java
  src/main/java/bjs/zangbu/security/account/dto/request/AuthRequest.java
  src/main/java/bjs/zangbu/security/account/dto/response/AuthResponse.java
  src/main/java/bjs/zangbu/security/account/service/AuthService.java
  src/main/java/bjs/zangbu/security/account/service/AuthServiceImpl.java
  src/main/java/bjs/zangbu/security/config/SecurityConfig.java
  src/main/java/bjs/zangbu/security/config/SecurityInitializer.java
  src/main/java/bjs/zangbu/security/filter/AuthenticationErrorFilter.java
  src/main/java/bjs/zangbu/security/filter/JwtAuthenticationFilter.java
  src/main/java/bjs/zangbu/security/filter/JwtUsernamePasswordAuthenticationFilter.java
  src/main/java/bjs/zangbu/security/handler/CustomAccessDeniedHandler.java
  src/main/java/bjs/zangbu/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/bjs/zangbu/security/handler/LoginFailureHandler.java
  src/main/java/bjs/zangbu/security/handler/LoginSuccessHandler.java
  src/main/java/bjs/zangbu/security/util/JsonResponse.java
  src/test/java/bjs/zangbu/chat/mapper/ChatMapperTest.java
  src/test/java/bjs/zangbu/deal/controller/DealControllerTest.java
  src/test/java/bjs/zangbu/deal/mapper/DealMapperTest.java
  src/test/java/bjs/zangbu/deal/vo/DealTest.java
  src/test/java/bjs/zangbu/notification/mapper/NotificationMapperTest.java
Labels: 🔨 fix, 🛠️ chore, 🐱해인

#208 docs: deal swagger 작성
  src/main/java/bjs/zangbu/deal/controller/DealController.java
  src/main/java/bjs/zangbu/deal/dto/request/DealRequest.java
  src/main/java/bjs/zangbu/deal/dto/response/DealResponse.java
  src/main/java/bjs/zangbu/deal/dto/response/DealWaitingListResponse.java
  src/main/java/bjs/zangbu/global/config/SwaggerConfig.java
  src/main/java/bjs/zangbu/security/config/SecurityConfig.java
Labels: 📃 docs, 🐱해인

#211 test: Codef TwoFactorService test
  src/main/java/bjs/zangbu/codef/encryption/CodefEncryption.java
  src/main/java/bjs/zangbu/codef/service/CodefServiceImpl.java
  src/test/java/bjs/zangbu/codef/service/CodefTwoFactorServiceImplTest.java
Labels: 📝 test, 🐯 현빈

#213 feat: ncp mime type 확인 및 테스트
  erl_crash.dump
  src/main/java/bjs/zangbu/deal/controller/DealController.java
  src/main/java/bjs/zangbu/ncp/auth/Holder.java
  src/main/java/bjs/zangbu/ncp/service/Base64UploaderService.java
  src/main/java/bjs/zangbu/ncp/service/Base64UploaderServiceImpl.java
  src/main/java/bjs/zangbu/ncp/service/BinaryUploaderService.java
  src/main/java/bjs/zangbu/ncp/service/BinaryUploaderServiceImpl.java
  src/main/java/bjs/zangbu/ncp/service/MultipartUploaderService.java
  src/main/java/bjs/zangbu/ncp/service/MultipartUploaderServiceImpl.java
  src/main/java/bjs/zangbu/ncp/service/PathUploaderService.java
  src/main/java/bjs/zangbu/ncp/service/PathUploaderServiceImpl.java
  src/main/java/bjs/zangbu/ncp/util/UploadUtil.java
  src/test/java/bjs/zangbu/ncp/auth/HolderTest.java
  src/test/java/bjs/zangbu/ncp/service/Base64UploaderServiceTest.java
  src/test/java/bjs/zangbu/ncp/service/BinaryUploaderServiceTest.java
  src/test/java/bjs/zangbu/ncp/service/MultipartUploaderServiceTest.java
  src/test/java/bjs/zangbu/ncp/service/PathUploaderServiceTest.java
Labels: ⭐ feat, 📝 test, 🐱해인

#214 feat: CodefThread 성능 개선 및 오류 개선
  src/main/java/bjs/zangbu/building/controller/BuildingController.java
  src/main/java/bjs/zangbu/building/controller/MainController.java
  src/main/java/bjs/zangbu/codef/service/CodefTwoFactorServiceImpl.java
  src/main/java/bjs/zangbu/codef/thread/CodefThread.java
  src/test/java/bjs/zangbu/codef/service/CodefTwoFactorServiceImplTest.java
Labels: ⭐ feat, 🐯 현빈

#215 test: 테스트 로그 정리 및 root controller 생성
  build.gradle
  src/main/java/bjs/zangbu/global/config/ServletConfig.java
  src/main/java/bjs/zangbu/global/controller/RootController.java
  src/main/java/bjs/zangbu/global/exception/GlobalExceptionHandler.java
  src/main/java/bjs/zangbu/publicdata/controller/trade/OfficeRentController.java
  src/main/java/bjs/zangbu/scheduler/controller/NotificationSchedulerController.java
  src/main/resources/log4j2.xml
Labels: 📝 test, 🐱해인

#216 fix: ncp 개행문자 처리 추가
  src/main/java/bjs/zangbu/ncp/service/Base64UploaderServiceImpl.java
  src/test/java/bjs/zangbu/ncp/service/Base64UploaderServiceTest.java
Labels: 🔨 fix, 🐱해인

#220 feat: pdf to ncp
  src/main/java/bjs/zangbu/deal/controller/DealController.java
  src/main/java/bjs/zangbu/deal/dto/response/BuildingRegisterResponse.java
  src/main/java/bjs/zangbu/deal/dto/response/DownloadUrlResponse.java
  src/main/java/bjs/zangbu/deal/service/ContractService.java
  src/main/java/bjs/zangbu/deal/service/ContractServiceImpl.java
  src/main/java/bjs/zangbu/deal/util/PdfUtil.java
  src/test/java/bjs/zangbu/deal/service/ContractServiceImplTest.java
Labels: ⭐ feat, 🍍 경환

#222 test: deal service, mapper 테스트 코드 작성
  .gitignore
  build.gradle
  src/main/java/bjs/zangbu/chat/config/WebSocketConfig.java
  src/main/java/bjs/zangbu/deal/controller/DealController.java
  src/main/java/bjs/zangbu/deal/dto/join/DealDocumentInfo.java
  src/main/java/bjs/zangbu/deal/dto/join/DealWithChatRoom.java
  src/main/java/bjs/zangbu/deal/dto/join/DealWithSaleType.java
  src/main/java/bjs/zangbu/deal/dto/request/DealRequest.java
  src/main/java/bjs/zangbu/deal/dto/request/EstateRegistrationRequest.java
  src/main/java/bjs/zangbu/deal/dto/response/DealResponse.java
  src/main/java/bjs/zangbu/deal/dto/response/DealWaitingListResponse.java
  src/main/java/bjs/zangbu/deal/mapper/DealMapper.java
  src/main/java/bjs/zangbu/deal/service/DealService.java
  src/main/java/bjs/zangbu/deal/service/DealServiceImpl.java
  src/main/java/bjs/zangbu/deal/vo/Deal.java
  src/main/java/bjs/zangbu/deal/vo/DealEnum.java
  src/main/java/bjs/zangbu/global/formatter/PrettyJsonFormatter.java
  src/main/java/bjs/zangbu/ncp/service/Base64UploaderService.java
  src/main/java/bjs/zangbu/ncp/service/BinaryUploaderService.java
  src/main/java/bjs/zangbu/ncp/service/MultipartUploaderService.java
  src/main/java/bjs/zangbu/ncp/service/PathUploaderService.java
  src/main/java/bjs/zangbu/security/config/SecurityConfig.java
  src/main/resources/bjs/zangbu/deal/mapper/DealMapper.xml
  src/main/resources/bjs/zangbu/imageList/mapper/ImageListMapper.xml
  src/main/resources/log4j2.xml
  src/test/java/bjs/zangbu/deal/mapper/DealMapperTest.java
  src/test/java/bjs/zangbu/deal/service/DealServiceTest.java
Labels: 📝 test, 🐱해인

#223 chore: response 한글 인코딩 문제 해결
  .gitignore
  src/main/java/bjs/zangbu/global/config/ServletConfig.java
Labels: 🛠️ chore, 🐱해인

#224 refactor: 회원가입 로직 수정
  src/main/java/bjs/zangbu/member/controller/MemberController.java
  src/main/java/bjs/zangbu/member/dto/request/MemberRequest.java
  src/main/java/bjs/zangbu/member/dto/response/MemberResponse.java
  src/main/java/bjs/zangbu/security/account/client/PassApiClient.java
  src/main/java/bjs/zangbu/security/account/controller/AuthController.java
  src/main/java/bjs/zangbu/security/account/dto/request/AuthRequest.java
  src/main/java/bjs/zangbu/security/account/dto/response/AuthResponse.java
  src/main/java/bjs/zangbu/security/account/service/AuthService.java
  src/main/java/bjs/zangbu/security/account/service/AuthServiceImpl.java
  src/main/resources/bjs/zangbu/security/account/mapper/AuthMapper.xml
Labels: ♻️ refactor, 🐳 소정

#228 초본 api로부터 주소 저장하기
  src/main/java/bjs/zangbu/addressChange/dto/abstractResponse/ResidentAbstractResponse.java
  src/main/java/bjs/zangbu/addressChange/dto/abstractResponse/ResidentDataResponse.java
  src/main/java/bjs/zangbu/addressChange/dto/request/ResRegisterCertRequest.java
  src/main/java/bjs/zangbu/addressChange/service/AddressChangeService.java
  src/main/java/bjs/zangbu/addressChange/service/AddressChangeServiceImpl.java
  src/main/java/bjs/zangbu/addressChange/util/JusoClient.java
  src/main/java/bjs/zangbu/codef/service/CodefServiceImpl.java
  src/main/java/bjs/zangbu/codef/service/CodefTwoFactorServiceImpl.java
  src/main/java/bjs/zangbu/security/account/dto/request/AuthRequest.java
  src/test/java/bjs/zangbu/addressChange/service/AddressChangeServiceImplTest.java
  src/test/java/bjs/zangbu/codef/service/CodefTwoFactorServiceImplTest.java
Labels: ♻️ refactor, ⭐ feat, 📝 test, 🍍 경환

#230 test: 결제 테스트 구현
  build.gradle
  gradlew
  src/main/java/bjs/zangbu/payment/controller/PaymentController.java
  src/main/java/bjs/zangbu/payment/mapper/PaymentMapper.java
  src/main/java/bjs/zangbu/payment/service/PaymentService.java
  src/main/java/bjs/zangbu/payment/service/PaymentServiceImpl.java
  src/main/java/bjs/zangbu/review/dto/response/ReviewListResponse.java
  src/main/resources/bjs/zangbu/payment/mapper/PaymentMapper.xml
  src/test/java/bjs/zangbu/payment/controller/PaymentControllerTest.java
  src/test/java/bjs/zangbu/payment/service/PaymentEntitlementFlowTest.java
  src/test/java/bjs/zangbu/payment/service/PaymentServiceTest.java
Labels: ♻️ refactor, 📝 test, 🍾영오

#233 test: 리뷰 테스트 구현
  REVIEW_TEST_SUMMARY.md
  gradlew
  src/main/java/bjs/zangbu/review/controller/ReviewController.java
  src/main/java/bjs/zangbu/review/dto/request/ReviewCreateRequest.java
  src/main/java/bjs/zangbu/review/dto/response/ReviewDetailResponse.java
  src/main/java/bjs/zangbu/review/mapper/ReviewInsertParam.java
  src/main/java/bjs/zangbu/review/mapper/ReviewMapper.java
  src/main/java/bjs/zangbu/review/service/ReviewServiceImpl.java
  src/main/resources/bjs/zangbu/review/mapper/ReviewMapper.xml
  src/test/java/bjs/zangbu/config/TestConfig.java
  src/test/java/bjs/zangbu/review/controller/ReviewControllerIntegrationTest.java
  src/test/java/bjs/zangbu/review/controller/ReviewControllerTest.java
  src/test/java/bjs/zangbu/review/mapper/ReviewMapperTest.java
  src/test/java/bjs/zangbu/review/service/ReviewServiceImplTest.java
  src/test/java/bjs/zangbu/review/service/ReviewServiceIntegrationTest.java
Labels: 📝 test, 🍾영오

#234 test: member/auth mapper 테스트 작성
  src/main/java/bjs/zangbu/member/dto/join/BookmarkBuilding.java
  src/main/java/bjs/zangbu/member/mapper/MemberMapper.java
  src/main/java/bjs/zangbu/member/service/MemberService.java
  src/main/java/bjs/zangbu/member/service/MemberServiceImpl.java
  src/main/java/bjs/zangbu/security/account/mapper/AuthMapper.java
  src/main/java/bjs/zangbu/security/account/vo/Member.java
  src/main/resources/bjs/zangbu/member/mapper/MemberMapper.xml
  src/main/resources/bjs/zangbu/security/account/mapper/AuthMapper.xml
  src/test/java/bjs/zangbu/member/mapper/MemberMapperTest.java
  src/test/java/bjs/zangbu/security/account/mapper/AuthMapperTest.java
Labels: 📝 test, 🐳 소정

#239 Feat : 등기부 등본 api 테스트
  src/main/java/bjs/zangbu/codef/service/CodefService.java
  src/main/java/bjs/zangbu/codef/service/CodefServiceImpl.java
  src/main/java/bjs/zangbu/codef/service/CodefTwoFactorService.java
  src/main/java/bjs/zangbu/codef/service/CodefTwoFactorServiceImpl.java
  src/main/java/bjs/zangbu/deal/controller/DealController.java
  src/main/java/bjs/zangbu/deal/dto/request/EstateRegistrationRequest.java
  src/main/java/bjs/zangbu/deal/dto/response/EstateRegistrationResponse.java
  src/main/java/bjs/zangbu/deal/service/ContractService.java
  src/main/java/bjs/zangbu/deal/service/ContractServiceImpl.java
  src/test/java/bjs/zangbu/deal/service/ContractServiceImplTest.java
Labels: ♻️ refactor, ⭐ feat, 📝 test, 🍍 경환

#242 feat: 최근 리뷰 3개 불러오는 메서드 구현
  src/main/java/bjs/zangbu/review/dto/response/ReviewListResponse.java
  src/main/java/bjs/zangbu/review/service/ReviewService.java
  src/main/java/bjs/zangbu/review/service/ReviewServiceImpl.java
  src/main/resources/bjs/zangbu/review/mapper/ReviewMapper.xml
  src/test/java/bjs/zangbu/review/service/ReviewServiceIntegrationTest.java
Labels: ⭐ feat, 🍾영오

#245 refactor: 최근 리뷰 3개 불러오는 기능 수정
  src/main/java/bjs/zangbu/review/controller/ReviewController.java
  src/main/java/bjs/zangbu/review/dto/response/ReviewListResponse.java
  src/main/java/bjs/zangbu/review/service/ReviewService.java
  src/main/java/bjs/zangbu/review/service/ReviewServiceImpl.java
  src/main/java/bjs/zangbu/review/vo/ReviewListResponseVO.java
  src/test/java/bjs/zangbu/config/TestConfig.java
  src/test/java/bjs/zangbu/review/controller/ReviewControllerIntegrationTest.java
  src/test/java/bjs/zangbu/review/controller/ReviewControllerTest.java
  src/test/java/bjs/zangbu/review/service/ReviewServiceImplTest.java
  src/test/java/bjs/zangbu/review/service/ReviewServiceIntegrationTest.java
Labels: ♻️ refactor, 📝 test, 🍾영오

#256 test: Building/Main 테스트
  src/main/java/bjs/zangbu/building/controller/BuildingController.java
  src/main/java/bjs/zangbu/building/mapper/BuildingMapper.java
  src/main/resources/bjs/zangbu/building/mapper/BuildingMapper.xml
Labels: 📝 test, 🐯 현빈

#258 test: 일련번호
  src/main/java/bjs/zangbu/building/dto/request/BuildingRequest.java
  src/main/java/bjs/zangbu/building/vo/Building.java
  src/main/java/bjs/zangbu/codef/controller/CodefController.java
  src/main/java/bjs/zangbu/codef/dto/response/CodefResponse.java
  src/main/java/bjs/zangbu/security/util/JwtProcessor.java
  src/main/resources/bjs/zangbu/building/mapper/BuildingMapper.xml
  src/test/java/bjs/zangbu/building/mapper/BuildingMapperTest.java
  src/test/java/bjs/zangbu/building/service/BuildingServiceTest.java
Labels: 📝 test, 🐯 현빈

#290 refactor: 주석 제거 및 로직 수정
  src/main/java/bjs/zangbu/addressChange/service/AddressChangeServiceImpl.java
  src/main/java/bjs/zangbu/codef/controller/CodefController.java
  src/main/java/bjs/zangbu/codef/service/CodefTwoFactorServiceImpl.java
  src/main/java/bjs/zangbu/global/config/RedisConfig.java
  src/main/java/bjs/zangbu/security/account/controller/AuthController.java
  src/main/java/bjs/zangbu/security/account/dto/request/AuthRequest.java
  src/main/java/bjs/zangbu/security/account/dto/response/AuthResponse.java
  src/main/java/bjs/zangbu/security/account/service/AuthService.java
  src/main/java/bjs/zangbu/security/account/service/AuthServiceImpl.java
  src/main/java/bjs/zangbu/security/config/SecurityConfig.java
  src/main/resources/bjs/zangbu/addressChange/mapper/AddressChangeMapper.xml
Labels: ♻️ refactor, ⭐ feat, 🐳 소정

#293 refactor: 매물등록 쿼리문 리팩터링
  src/main/java/bjs/zangbu/codef/controller/CodefController.java
  src/main/java/bjs/zangbu/global/config/RedisConfig.java
  src/main/resources/bjs/zangbu/complexList/mapper/ComplexListMapper.xml
Labels: ♻️ refactor, 🐯 현빈

#297 refactor: 채팅 수정
  build.gradle
  src/main/java/bjs/zangbu/chat/config/WebSocketConfig.java
  src/main/java/bjs/zangbu/chat/controller/ChatController.java
  src/main/java/bjs/zangbu/chat/controller/ChatStompController.java
  src/main/java/bjs/zangbu/chat/dto/request/ChatRequest.java
  src/main/java/bjs/zangbu/chat/dto/response/ChatResponse.java
  src/main/java/bjs/zangbu/chat/service/ChatServiceImpl.java
  src/main/java/bjs/zangbu/deal/service/DealServiceImpl.java
  src/main/java/bjs/zangbu/global/config/ServletConfig.java
  src/main/java/bjs/zangbu/notification/service/NotificationService.java
  src/main/java/bjs/zangbu/security/config/SecurityConfig.java
  src/main/java/bjs/zangbu/security/filter/AuthenticationErrorFilter.java
  src/main/java/bjs/zangbu/security/util/JwtProcessor.java
  src/main/webapp/resources/assets/Image_fx-iZMVMA4I.jpg
  src/main/webapp/resources/assets/MembershipView-Bj6H9WD9.js
  src/main/webapp/resources/assets/MembershipView-tn0RQdqM.css
  src/main/webapp/resources/assets/fa-brands-400-DFY6gyJh.woff2
  src/main/webapp/resources/assets/fa-regular-400-DdcaUAxu.woff2
  src/main/webapp/resources/assets/fa-solid-900-BQpGBb1f.woff2
  src/main/webapp/resources/assets/fa-v4compatibility-BHaDpj3C.woff2
  src/main/webapp/resources/assets/index-D_6qN3Je.css
  src/main/webapp/resources/assets/index-xsOzOzeH.js
  src/main/webapp/resources/assets/login_image-DFZJ9uFv.png
  src/main/webapp/resources/assets/logo-M_BBjVdl.png
  src/main/webapp/resources/assets/real-estate-CcLIKbBF.js
  src/main/webapp/resources/assets/signup_image-DfsMiRLt.png
  src/main/webapp/resources/favicon.ico
  src/main/webapp/resources/firebase-messaging-sw.js
  src/main/webapp/resources/index.html
  src/test/java/bjs/zangbu/chat/jwtTest.java
  src/test/java/bjs/zangbu/chat/passwordTest.java
Labels: ♻️ refactor, 🎸수연

#299 test: Building, Main 에러 처리
  src/main/java/bjs/zangbu/building/dto/response/MainResponse.java
  src/main/resources/bjs/zangbu/building/mapper/BuildingMapper.xml
Labels: 📝 test, 🐯 현빈

#308 feat: api 추가
  src/main/java/bjs/zangbu/deal/controller/DealController.java
  src/main/java/bjs/zangbu/deal/dto/response/DealResponse.java
  src/main/java/bjs/zangbu/deal/service/DealService.java
  src/main/java/bjs/zangbu/deal/service/DealServiceImpl.java
  src/main/java/bjs/zangbu/global/config/RedisConfig.java
  src/main/java/bjs/zangbu/security/config/SecurityConfig.java
Labels: ⭐ feat, 🐱 해인
