Repository BackJinSa/zangBu_Back, pull requests merged in 2025-07, with the labels that each got.

#9 feat:vo생성
  build.gradle
  src/main/java/bjs/zangbu/deal/vo/Deal.java
  src/main/java/bjs/zangbu/deal/vo/DealEnum.java
  src/test/java/bjs/zangbu/deal/vo/DealTest.java
  src/test/java/bjs/zangbu/global/encryption/Base64EncryptionTest.java
  src/test/java/bjs/zangbu/global/encryption/RSAEncryptionTest.java
Labels: ⭐ feat, 🐱해인

#15 chore:yml 개발
  build.gradle
  src/main/java/bjs/zangbu/global/config/RootConfig.java
  src/main/java/bjs/zangbu/global/config/YamlPropertyConfig.java
Labels: 🛠️ chore, 🐯 현빈

#20 feat:Building vo 생성
  src/main/java/bjs/zangbu/building/vo/Building.java
  src/main/java/bjs/zangbu/building/vo/PropertyType.java
  src/main/java/bjs/zangbu/building/vo/SellerType.java
Labels: ⭐ feat, 🐯 현빈

#21 feat:deal dto 개발
  src/main/java/bjs/zangbu/deal/dto/request/DealRequest.java
  src/main/java/bjs/zangbu/deal/dto/response/DealResponse.java
  src/main/java/bjs/zangbu/deal/dto/response/DealWaitingListResponse.java
  src/main/java/bjs/zangbu/deal/vo/Deal.java
Labels: ⭐ feat, 🐱해인

#24 feat : deal/service created
  src/main/java/bjs/zangbu/deal/service/DealService.java
  src/main/java/bjs/zangbu/deal/service/DealServiceImpl.java
Labels: ⭐ feat, 🍍 경환

#26 Feat/#5
  build.gradle
  src/main/java/bjs/zangbu/security/account/vo/User.java
  src/main/java/bjs/zangbu/security/account/vo/UserEnum.java
  src/main/java/bjs/zangbu/user/controller/UserController.java
  src/main/java/bjs/zangbu/user/mapper/UserMapper.java
  src/main/java/bjs/zangbu/user/service/UserService.java
  src/main/java/bjs/zangbu/user/service/UserServiceImpl.java
  src/main/resources/bjs/zangbu/mapper/MapperTemplate.xml
Labels: ⭐ feat, 🐳 소정

#29 chore:controller랑 dto 클래스명 통일
  src/main/java/bjs/zangbu/deal/controller/DealController.java
  src/main/java/bjs/zangbu/deal/dto/request/DealRequest.java
  src/main/java/bjs/zangbu/deal/dto/response/DealResponse.java
Labels: 🛠️ chore

#30 feat : service 기본 구조 설계
  src/main/java/bjs/zangbu/notification/dto/request/NotificationRequest.java
  src/main/java/bjs/zangbu/notification/dto/response/NotificationResponse.java
  src/main/java/bjs/zangbu/notification/service/NotificationService.java
  src/test/java/bjs/zangbu/notification/mapper/NotificationMapperTest.java
Labels: ⭐ feat, ⚽ 경민

#32 feat: Chat vo 생성
  src/main/java/bjs/zangbu/chat/controller/ChatController.java
  src/main/java/bjs/zangbu/chat/dto/ChatMessageDTO.java
  src/main/java/bjs/zangbu/chat/dto/ChatRoomDTO.java
  src/main/java/bjs/zangbu/chat/service/ChatService.java
  src/main/java/bjs/zangbu/chat/service/ChatServiceImpl.java
  src/main/java/bjs/zangbu/chat/vo/ChatMessage.java
  src/main/java/bjs/zangbu/chat/vo/ChatRoom.java
  src/main/resources/bjs/zangbu/chat/mapper/ChatMapper.xml
Labels: ⭐ feat, 🎸수연

#37 feat:매물 상세보기 기능 개발
  src/main/java/bjs/zangbu/building/controller/BuildingController.java
  src/main/java/bjs/zangbu/building/mapper/BuildingMapper.java
  src/main/java/bjs/zangbu/building/service/BuildingService.java
  src/main/java/bjs/zangbu/building/service/BuildingServiceImpl.java
  src/main/resources/bjs/zangbu/building/mapper/BuildingMapper.xml
Labels: ⭐ feat, 🐯 현빈

#36 feat:Codef 외부 API 기능 개발
  src/main/java/bjs/zangbu/codef/converter/CodefConverter.java
  src/main/java/bjs/zangbu/codef/encryption/CodefEncryption.java
  src/main/java/bjs/zangbu/codef/service/CodefService.java
  src/main/java/bjs/zangbu/codef/service/CodefServiceImpl.java
Labels: ⭐ feat, 🐯 현빈

#28 feat: map의 list 기능 구현
  src/main/java/bjs/zangbu/map/controller/MapController.java
  src/main/java/bjs/zangbu/map/dto/request/MapListRequest.java
  src/main/java/bjs/zangbu/map/dto/request/MapRequest.java
  src/main/java/bjs/zangbu/map/dto/response/MapListResponse.java
  src/main/java/bjs/zangbu/map/dto/response/MapResponse.java
  src/main/java/bjs/zangbu/map/map구현.md
  src/main/java/bjs/zangbu/map/service/MapService.java
  src/main/java/bjs/zangbu/map/service/MapServiceImpl.java
  src/main/java/bjs/zangbu/map/util/CodefClient.java
Labels: ⭐ feat, 🍾영오

#44 feat: member/auth dto, vo 개발
  src/main/java/bjs/zangbu/member/controller/UserController.java
  src/main/java/bjs/zangbu/member/dto/request/MemberRequest.java
  src/main/java/bjs/zangbu/member/dto/response/MemberResponse.java
  src/main/java/bjs/zangbu/member/mapper/UserMapper.java
  src/main/java/bjs/zangbu/member/service/UserService.java
  src/main/java/bjs/zangbu/member/service/UserServiceImpl.java
  src/main/java/bjs/zangbu/security/account/dto/request/AuthRequest.java
  src/main/java/bjs/zangbu/security/account/dto/response/AuthResponse.java
  src/main/java/bjs/zangbu/security/account/mapper/UserDetailsMapper.java
  src/main/java/bjs/zangbu/security/account/vo/CustomUser.java
  src/main/java/bjs/zangbu/security/account/vo/Member.java
  src/main/java/bjs/zangbu/security/account/vo/MemberEnum.java
  src/main/java/bjs/zangbu/user/controller/UserController.java
  src/main/java/bjs/zangbu/user/mapper/UserMapper.java
  src/main/java/bjs/zangbu/user/service/UserService.java
Labels: ⭐ feat, 🐳 소정

#49 feat : notification mapper/xml/response/request 구현
  src/main/java/bjs/zangbu/notification/controller/NotificationController.java
  src/main/java/bjs/zangbu/notification/dto/request/NotificationRequest.java
  src/main/java/bjs/zangbu/notification/dto/response/NotificationResponse.java
  src/main/java/bjs/zangbu/notification/mapper/NotificationMapper.java
  src/main/java/bjs/zangbu/notification/service/NotificationService.java
  src/main/java/bjs/zangbu/notification/service/NotificationServiceImpl.java
  src/main/java/bjs/zangbu/notification/vo/Notification.java
  src/main/java/bjs/zangbu/notification/vo/TypeDetail.java
  src/main/resources/bjs/zangbu/notification/mapper/NotificationMapper.xml
  src/test/java/bjs/zangbu/notification/mapper/NotificationMapperTest.java
Labels: ⭐ feat, ⚽ 경민

#50 feat:deal service 개발
  src/main/java/bjs/zangbu/deal/controller/DealController.java
  src/main/java/bjs/zangbu/deal/dto/join/DealWithChatRoom.java
  src/main/java/bjs/zangbu/deal/dto/response/DealResponse.java
  src/main/java/bjs/zangbu/deal/dto/response/DealWaitingListResponse.java
  src/main/java/bjs/zangbu/deal/mapper/DealMapper.java
  src/main/java/bjs/zangbu/deal/service/DealService.java
  src/main/java/bjs/zangbu/deal/service/DealServiceImpl.java
  src/main/java/bjs/zangbu/deal/vo/Deal.java
  src/main/resources/bjs/zangbu/deal/DealMapper.xml
Labels: ⭐ feat, 🐱해인

#48 feat: map/category 기능 구현
  src/main/java/bjs/zangbu/map/controller/MapController.java
  src/main/java/bjs/zangbu/map/dto/request/MapCategoryRequest.java
  src/main/java/bjs/zangbu/map/dto/response/MapCategoryResponse.java
  src/main/java/bjs/zangbu/map/service/MapService.java
  src/main/java/bjs/zangbu/map/service/MapServiceImpl.java
  src/main/java/bjs/zangbu/map/util/KakaoMapClient.java
Labels: ⭐ feat, 🍾영오

#53 feat:Building Service, Controller 개발
  src/main/java/bjs/zangbu/bookmark/mapper/BookMarkMapper.java
  src/main/java/bjs/zangbu/building/controller/BuildingController.java
  src/main/java/bjs/zangbu/building/dto/request/BuildingRequest.java
  src/main/java/bjs/zangbu/building/dto/response/BuildingResponse.java
  src/main/java/bjs/zangbu/building/mapper/BuildingMapper.java
  src/main/java/bjs/zangbu/building/service/BuildingService.java
  src/main/java/bjs/zangbu/building/service/BuildingServiceImpl.java
  src/main/java/bjs/zangbu/building/vo/Building.java
  src/main/java/bjs/zangbu/complexList/mapper/ComplexListMapper.java
  src/main/java/bjs/zangbu/complexList/vo/ComplexList.java
  src/main/java/bjs/zangbu/imageList/mapper/ImageListMapper.java
  src/main/java/bjs/zangbu/imageList/vo/ImageList.java
  src/main/resources/bjs/zangbu/MapperTemplate.xml
  src/main/resources/bjs/zangbu/bookmark/mapper/BookMarkMapper.xml
  src/main/resources/bjs/zangbu/building/mapper/BuildingMapper.xml
  src/main/resources/bjs/zangbu/complexList/mapper/ComplexListMapper.xml
  src/main/resources/bjs/zangbu/imageList/mapper/ImageListMapper.xml
Labels: ⭐ feat, 🐯 현빈

#59 Feature/deal report
  src/main/java/bjs/zangbu/deal/controller/DealController.java
  src/main/java/bjs/zangbu/deal/dto/join/DealWithSaleType.java
  src/main/java/bjs/zangbu/deal/mapper/DealMapper.java
  src/main/java/bjs/zangbu/deal/service/ContractService.java
  src/main/java/bjs/zangbu/deal/service/ContractServiceImpl.java
  src/main/java/bjs/zangbu/global/config/ServletConfig.java
  src/main/resources/bjs/zangbu/deal/mapper/DealMapper.xml
  src/main/resources/contracts/lease_contract.pdf
  src/main/resources/contracts/sale_contract.pdf
  src/test/java/bjs/zangbu/deal/controller/DealControllerTest.java
Labels: ⭐ feat, 📝 test, 🍍 경환

#64 feat:imageListService 기능 개발
  src/main/java/bjs/zangbu/imageList/mapper/ImageListMapper.java
  src/main/java/bjs/zangbu/imageList/service/ImageListService.java
  src/main/java/bjs/zangbu/imageList/service/ImageListServiceImpl.java
  src/main/resources/bjs/zangbu/imageList/mapper/ImageListMapper.xml
Labels: ⭐ feat, 🐯 현빈

#65 feat: notification service 구현, vo/response/request/mapper 수정
  src/main/java/bjs/zangbu/notification/controller/NotificationController.java
  src/main/java/bjs/zangbu/notification/dto/request/NotificationRequest.java
  src/main/java/bjs/zangbu/notification/dto/response/NotificationResponse.java
  src/main/java/bjs/zangbu/notification/mapper/NotificationMapper.java
  src/main/java/bjs/zangbu/notification/service/NotificationService.java
  src/main/java/bjs/zangbu/notification/service/NotificationServiceImpl.java
  src/main/java/bjs/zangbu/notification/vo/Notification.java
  src/main/resources/bjs/zangbu/notification/mapper/NotificationMapper.xml
Labels: ⭐ feat, ⚽ 경민

#70 feat: imageService
  src/main/java/bjs/zangbu/deal/controller/DealController.java
  src/main/java/bjs/zangbu/deal/dto/join/DealWithChatRoom.java
  src/main/java/bjs/zangbu/deal/dto/request/DealRequest.java
  src/main/java/bjs/zangbu/deal/dto/response/DealResponse.java
  src/main/java/bjs/zangbu/deal/dto/response/DealWaitingListResponse.java
  src/main/java/bjs/zangbu/deal/mapper/DealMapper.java
  src/main/java/bjs/zangbu/deal/service/DealService.java
  src/main/java/bjs/zangbu/deal/service/DealServiceImpl.java
  src/main/java/bjs/zangbu/deal/vo/Deal.java
  src/main/resources/bjs/zangbu/deal/mapper/DealMapper.xml
  src/test/java/bjs/zangbu/deal/controller/DealControllerTest.java
  src/test/java/bjs/zangbu/deal/vo/DealTest.java
Labels: ⭐ feat, 🐱해인

#79 feat: chat service 작성
  src/main/java/bjs/zangbu/chat/mapper/ChatMapper.java
  src/main/java/bjs/zangbu/chat/service/ChatService.java
  src/main/java/bjs/zangbu/chat/service/ChatServiceImpl.java
  src/main/resources/bjs/zangbu/chat/mapper/ChatMapper.xml
Labels: ⭐ feat, 🎸수연

#81 feat: review 목록 불러오는 기능 구현(페이지네이션 수정)
  src/main/java/bjs/zangbu/map/map구현.md
  src/main/java/bjs/zangbu/review/controller/ReviewController.java
  src/main/java/bjs/zangbu/review/dto/response/ReviewListResponse.java
  src/main/java/bjs/zangbu/review/dto/response/ReviewListResult.java
  src/main/java/bjs/zangbu/review/mapper/ReviewMapper.java
  src/main/java/bjs/zangbu/review/service/ReviewService.java
  src/main/java/bjs/zangbu/review/service/ReviewServiceImpl.java
  src/main/resources/bjs/zangbu/review/mapper/ReviewMapper.xml
Labels: ⭐ feat, 🍾영오

#90 feat: security 설정
  build.gradle
  src/main/java/bjs/zangbu/global/config/WebConfig.java
  src/main/java/bjs/zangbu/security/account/dto/request/AuthRequest.java
  src/main/java/bjs/zangbu/security/account/mapper/UserDetailsMapper.java
  src/main/java/bjs/zangbu/security/account/vo/Member.java
  src/main/java/bjs/zangbu/security/account/vo/MemberEnum.java
  src/main/java/bjs/zangbu/security/config/SecurityConfig.java
  src/main/java/bjs/zangbu/security/config/SecurityInitializer.java
  src/main/java/bjs/zangbu/security/filter/AuthenticationErrorFilter.java
  src/main/java/bjs/zangbu/security/filter/JwtAuthenticationFilter.java
  src/main/java/bjs/zangbu/security/filter/JwtUsernamePasswordAuthenticationFilter.java
  src/main/java/bjs/zangbu/security/handler/CustomAccessDeniedHandler.java
  src/main/java/bjs/zangbu/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/bjs/zangbu/security/handler/LoginFailureHandler.java
  src/main/java/bjs/zangbu/security/handler/LoginSuccessHandler.java
  src/main/java/bjs/zangbu/security/service/CustomUserDetailsService.java
  src/main/java/bjs/zangbu/security/util/JsonResponse.java
  src/main/java/bjs/zangbu/security/util/JwtProcessor.java
  src/main/resources/bjs/zangbu/security/account/mapper/UserDetailsMapper.xml
Labels: ⭐ feat, 🐳 소정

#91 feat:LocalDateTime formatter 추가
  src/main/java/bjs/zangbu/global/formatter/LocalDateFormatter.java
Labels: ⭐ feat, 🐱해인

#95 feat: review 삭제 기능 구현
  src/main/java/bjs/zangbu/review/controller/ReviewController.java
  src/main/java/bjs/zangbu/review/mapper/ReviewMapper.java
  src/main/java/bjs/zangbu/review/service/ReviewService.java
  src/main/java/bjs/zangbu/review/service/ReviewServiceImpl.java
  src/main/resources/bjs/zangbu/review/mapper/ReviewMapper.xml
Labels: ⭐ feat, 🍾영오

#97 refactor: Building, Main 에러 처리
  src/main/java/bjs/zangbu/building/controller/BuildingController.java
  src/main/java/bjs/zangbu/building/controller/MainController.java
  src/main/java/bjs/zangbu/building/exception/BuildingException.java
Labels: ♻️ refactor, 🐯 현빈

#100 feat: payment 결제 기능 구현
  src/main/java/bjs/zangbu/payment/controller/PaymentController.java
  src/main/java/bjs/zangbu/payment/dto/request/PaymentRequest.java
  src/main/java/bjs/zangbu/payment/dto/response/PaymentResponse.java
  src/main/java/bjs/zangbu/payment/mapper/PaymentInsertParam.java
  src/main/java/bjs/zangbu/payment/mapper/PaymentMapper.java
  src/main/java/bjs/zangbu/payment/service/PaymentService.java
  src/main/java/bjs/zangbu/payment/service/PaymentServiceImpl.java
  src/main/resources/bjs/zangbu/payment/mapper/PaymentMapper.xml
Labels: ⭐ feat, 🍾영오

#102 feat: chat에 rabbitMQ
  src/main/java/bjs/zangbu/chat/config/RabbitMQConfig.java
  src/main/java/bjs/zangbu/chat/config/WebSocketConfig.java
  src/main/java/bjs/zangbu/chat/controller/ChatStompController.java
  src/main/java/bjs/zangbu/chat/controller/ChatWebSocketController.java
  src/main/java/bjs/zangbu/chat/dto/request/ChatRequest.java
  src/main/java/bjs/zangbu/chat/dto/response/ChatResponse.java
  src/main/java/bjs/zangbu/chat/mapper/ChatMapper.java
  src/main/java/bjs/zangbu/chat/service/ChatService.java
  src/main/java/bjs/zangbu/chat/service/ChatServiceImpl.java
  src/main/java/bjs/zangbu/chat/vo/ChatMessage.java
  src/main/java/bjs/zangbu/chat/vo/ChatRoom.java
  src/main/java/bjs/zangbu/global/config/RootConfig.java
  src/main/resources/bjs/zangbu/chat/mapper/ChatMapper.xml
Labels: ⭐ feat, 🎸수연

#108 feat:CodefService 개발
  build.gradle
  src/main/java/bjs/zangbu/codef/controller/CodefController.java
  src/main/java/bjs/zangbu/codef/dto/request/CodefRequest.java
  src/main/java/bjs/zangbu/codef/exception/CodefException.java
  src/main/java/bjs/zangbu/codef/exception/EasyCodefMessageConstant.java
  src/main/java/bjs/zangbu/codef/service/CodefService.java
  src/main/java/bjs/zangbu/codef/service/CodefServiceImpl.java
  src/main/java/bjs/zangbu/codef/service/CodefTwoFactorService.java
  src/main/java/bjs/zangbu/codef/service/CodefTwoFactorServiceImpl.java
  src/main/java/bjs/zangbu/codef/session/CodefAuthSession.java
  src/main/java/bjs/zangbu/codef/thread/CodefThread.java
  src/main/java/bjs/zangbu/global/config/RedisConfig.java
  src/main/resources/bjs/zangbu/bookmark/mapper/BookMarkMapper.xml
Labels: ⭐ feat, 🐯 현빈

#109 feat:CodefService 개발
  src/main/java/bjs/zangbu/codef/exception/CodefException.java
  src/main/java/bjs/zangbu/codef/service/CodefService.java
  src/main/java/bjs/zangbu/codef/service/CodefServiceImpl.java
  src/main/java/bjs/zangbu/codef/service/CodefTwoFactorService.java
  src/main/java/bjs/zangbu/codef/service/CodefTwoFactorServiceImpl.java
Labels: ⭐ feat, 🐯 현빈

#114 feat: auth에 토큰 관련 기능 추가
  src/main/java/bjs/zangbu/security/account/controller/AuthController.java
  src/main/java/bjs/zangbu/security/account/dto/response/AuthResponse.java
  src/main/java/bjs/zangbu/security/account/service/AuthService.java
  src/main/java/bjs/zangbu/security/account/service/AuthServiceImpl.java
  src/main/java/bjs/zangbu/security/util/JwtProcessor.java
Labels: ⭐ feat, 🐳 소정

#116 feat: payment 결제 승인 요청 기능 구현
  src/main/java/bjs/zangbu/payment/config/RestConfig.java
  src/main/java/bjs/zangbu/payment/controller/PaymentController.java
  src/main/java/bjs/zangbu/payment/dto/request/PaymentConfirmRequest.java
  src/main/java/bjs/zangbu/payment/dto/response/PaymentConfirmResponse.java
  src/main/java/bjs/zangbu/payment/dto/response/PaymentResponse.java
  src/main/java/bjs/zangbu/payment/mapper/PaymentInsertParam.java
  src/main/java/bjs/zangbu/payment/mapper/PaymentMapper.java
  src/main/java/bjs/zangbu/payment/payment 작동 흐름.md
  src/main/java/bjs/zangbu/payment/service/PaymentService.java
  src/main/java/bjs/zangbu/payment/service/PaymentServiceImpl.java
  src/main/resources/bjs/zangbu/payment/mapper/PaymentMapper.xml
Labels: ♻️ refactor, ⭐ feat, 🍾영오

#118 feat: notification service 완료 fcm 완료
  .gitignore
  src/main/java/bjs/zangbu/deal/service/DealServiceImpl.java
  src/main/java/bjs/zangbu/fcm/config/FirebaseConfig.java
  src/main/java/bjs/zangbu/fcm/controller/FcmController.java
  src/main/java/bjs/zangbu/fcm/dto/request/FcmRequest.java
  src/main/java/bjs/zangbu/fcm/dto/response/FcmResponse.java
  src/main/java/bjs/zangbu/fcm/mapper/FcmMapper.java
  src/main/java/bjs/zangbu/fcm/service/FcmSender.java
  src/main/java/bjs/zangbu/fcm/service/FcmSenderImpl.java
  src/main/java/bjs/zangbu/fcm/service/FcmService.java
  src/main/java/bjs/zangbu/fcm/service/FcmServiceImpl.java
  src/main/java/bjs/zangbu/fcm/vo/Fcm.java
  src/main/java/bjs/zangbu/notification/controller/NotificationController.java
  src/main/java/bjs/zangbu/notification/mapper/NotificationMapper.java
  src/main/java/bjs/zangbu/notification/service/NotificationService.java
  src/main/java/bjs/zangbu/notification/service/NotificationServiceImpl.java
  src/main/java/bjs/zangbu/notification/vo/Notification.java
  src/main/resources/bjs/zangbu/fcm/mapper/FcmMapper.xml
  src/main/resources/bjs/zangbu/notification/mapper/NotificationMapper.xml
  src/test/java/bjs/zangbu/fcm/service/FcmSenderImplTest.java
Labels: ⭐ feat, ⚽ 경민

#119 feat: chat 기능 추가
  src/main/java/bjs/zangbu/chat/controller/ChatController.java
  src/main/java/bjs/zangbu/chat/dto/response/ChatResponse.java
  src/main/java/bjs/zangbu/chat/mapper/ChatMapper.java
  src/main/java/bjs/zangbu/chat/service/ChatService.java
  src/main/java/bjs/zangbu/chat/service/ChatServiceImpl.java
  src/main/java/bjs/zangbu/chat/vo/ChatMessage.java
  src/main/java/bjs/zangbu/chat/vo/ChatRoom.java
  src/main/resources/bjs/zangbu/chat/mapper/ChatMapper.xml
Labels: ⭐ feat, 🎸수연

#122 feat: 공공데이터 api 구현을 위한 문서 작성 및 폴더 초기 구조 생성
  src/main/java/bjs/zangbu/publicdata/client/ApiClient.java
  src/main/java/bjs/zangbu/publicdata/controller/Controller.java
  src/main/java/bjs/zangbu/publicdata/service/aptinfo/Service.java
  src/main/java/bjs/zangbu/publicdata/service/aptlist/Service.java
  src/main/java/bjs/zangbu/publicdata/service/law/Service.java
  src/main/java/bjs/zangbu/publicdata/service/managecost/Service.java
  src/main/java/bjs/zangbu/publicdata/service/trade/Service.java
  src/main/java/bjs/zangbu/publicdata/service/wage/Service.java
  src/main/java/bjs/zangbu/publicdata/공공데이터_설명.md
  src/main/java/bjs/zangbu/review/service/ReviewServiceImpl.java
  src/main/resources/bjs/zangbu/publicdata/mapper/Mapper.xml
Labels: ♻️ refactor, ⭐ feat, 🍾영오

#123 feat: member에 알림 기능 추가
  src/main/java/bjs/zangbu/member/controller/MemberController.java
  src/main/java/bjs/zangbu/member/dto/request/MemberRequest.java
  src/main/java/bjs/zangbu/member/dto/response/MemberResponse.java
  src/main/java/bjs/zangbu/member/mapper/MemberMapper.java
  src/main/java/bjs/zangbu/member/service/MemberService.java
  src/main/java/bjs/zangbu/member/service/MemberServiceImpl.java
  src/main/java/bjs/zangbu/security/account/controller/AuthController.java
  src/main/java/bjs/zangbu/security/filter/JwtAuthenticationFilter.java
  src/main/java/bjs/zangbu/security/util/JsonResponse.java
  src/main/java/bjs/zangbu/security/util/JwtProcessor.java
  src/main/resources/bjs/zangbu/member/mapper/MemberMapper.xml
Labels: ⭐ feat, 🐳 소정

#126 Feature/report register
  src/main/java/bjs/zangbu/codef/service/CodefServiceImpl.java
  src/main/java/bjs/zangbu/deal/controller/DealController.java
  src/main/java/bjs/zangbu/deal/dto/join/DealDocumentInfo.java
  src/main/java/bjs/zangbu/deal/mapper/DealMapper.java
  src/main/java/bjs/zangbu/deal/vo/DocumentType.java
  src/main/java/bjs/zangbu/documentReport/service/PdfExtractor.java
  src/main/resources/bjs/zangbu/deal/mapper/DealMapper.xml
Labels: ⭐ feat, 🍍 경환

#134 style: 주석 수정
  src/main/java/bjs/zangbu/bookmark/mapper/BookMarkMapper.java
  src/main/java/bjs/zangbu/bookmark/service/BookMarkService.java
  src/main/java/bjs/zangbu/bookmark/service/BookMarkServiceImpl.java
  src/main/java/bjs/zangbu/building/controller/BuildingController.java
  src/main/java/bjs/zangbu/building/controller/MainController.java
  src/main/java/bjs/zangbu/building/dto/request/BuildingRequest.java
  src/main/java/bjs/zangbu/building/dto/response/BuildingResponse.java
  src/main/java/bjs/zangbu/building/dto/response/MainResponse.java
  src/main/java/bjs/zangbu/building/mapper/BuildingMapper.java
  src/main/java/bjs/zangbu/building/service/BuildingService.java
  src/main/java/bjs/zangbu/building/service/BuildingServiceImpl.java
  src/main/java/bjs/zangbu/complexList/mapper/ComplexListMapper.java
  src/main/java/bjs/zangbu/complexList/service/ComplexListService.java
  src/main/java/bjs/zangbu/complexList/service/ComplexListServiceImpl.java
  src/main/java/bjs/zangbu/imageList/mapper/ImageListMapper.java
  src/main/java/bjs/zangbu/imageList/service/ImageListService.java
  src/main/java/bjs/zangbu/imageList/service/ImageListServiceImpl.java
  src/main/resources/bjs/zangbu/building/mapper/BuildingMapper.xml
Labels: ♻️ refactor, 💟 style, 🐯 현빈

#141 feat: Session Key 가져오는 클래스 개발
  src/main/java/bjs/zangbu/codef/thread/CodefSessionThread.java
Labels: ♻️ refactor, ⭐ feat, 🐯 현빈

#140 Feat/#6 Scheduler 설정/컨트롤러 완료, Notification 수정
  src/main/java/bjs/zangbu/fcm/config/FirebaseConfig.java
  src/main/java/bjs/zangbu/fcm/service/FcmSender.java
  src/main/java/bjs/zangbu/fcm/service/FcmSenderImpl.java
  src/main/java/bjs/zangbu/notification/controller/NotificationController.java
  src/main/java/bjs/zangbu/notification/service/NotificationServiceImpl.java
  src/main/java/bjs/zangbu/scheduler/config/SchedulingConfig.java
  src/main/java/bjs/zangbu/scheduler/controller/NotificationSchedulerController.java
  src/test/java/bjs/zangbu/fcm/service/FcmSenderImplTest.java
  src/test/java/bjs/zangbu/notification/mapper/NotificationMapperTest.java
Labels: ♻️ refactor, ⭐ feat, ⚽ 경민

#146 Feat: 건축물대장 api 설계
  src/main/java/bjs/zangbu/codef/service/CodefTwoFactorService.java
  src/main/java/bjs/zangbu/codef/service/CodefTwoFactorServiceImpl.java
  src/main/java/bjs/zangbu/deal/S3/S3Config.java
  src/main/java/bjs/zangbu/deal/S3/S3Uploader.java
  src/main/java/bjs/zangbu/deal/controller/DealController.java
  src/main/java/bjs/zangbu/deal/dto/response/BuildingRegisterResponse.java
  src/main/java/bjs/zangbu/deal/service/ContractServiceImpl.java
  src/main/java/bjs/zangbu/deal/util/PdfUtil.java
  src/main/java/bjs/zangbu/deal/vo/DocumentType.java
Labels: ⭐ feat, 🍍 경환

#147 feat: chat 에러 처리
  src/main/java/bjs/zangbu/chat/config/JwtHandshakeInterceptor.java
  src/main/java/bjs/zangbu/chat/config/WebSocketConfig.java
  src/main/java/bjs/zangbu/chat/controller/ChatController.java
  src/main/java/bjs/zangbu/chat/controller/ChatStompController.java
  src/main/java/bjs/zangbu/chat/dto/request/ChatRequest.java
  src/main/java/bjs/zangbu/chat/exception/ChatException.java
  src/main/java/bjs/zangbu/chat/mapper/ChatMapper.java
  src/main/java/bjs/zangbu/chat/service/ChatServiceImpl.java
  src/main/java/bjs/zangbu/chat/vo/ChatMessage.java
  src/main/java/bjs/zangbu/chat/vo/ChatRoom.java
  src/main/resources/bjs/zangbu/chat/mapper/ChatMapper.xml
Labels: ♻️ refactor, 🎸수연

#152 refactor: member에 에러 처리
  src/main/java/bjs/zangbu/member/controller/MemberController.java
  src/main/java/bjs/zangbu/member/dto/response/MemberResponse.java
  src/main/java/bjs/zangbu/member/mapper/MemberMapper.java
  src/main/java/bjs/zangbu/member/service/MemberService.java
  src/main/java/bjs/zangbu/member/service/MemberServiceImpl.java
Labels: ♻️ refactor, 🐳 소정

#153 docs: Building, Main Swagger UI 적용
  build.gradle
  src/main/java/bjs/zangbu/building/controller/BuildingController.java
  src/main/java/bjs/zangbu/building/controller/MainController.java
  src/main/java/bjs/zangbu/codef/thread/CodefSessionThread.java
  src/main/java/bjs/zangbu/global/config/ServletConfig.java
  src/main/java/bjs/zangbu/global/config/SwaggerConfig.java
Labels: 📃 docs, 🐯 현빈

#155 feat: 공공데이터 api 추가 - 국토교통부_공동주택관리비(개별사용료)정보제공서비스
  src/main/java/bjs/zangbu/publicdata/controller/managecost/privateuse/ManageCostController.java
  src/main/java/bjs/zangbu/publicdata/dto/managecost/privateuse/GasCost.java
  src/main/java/bjs/zangbu/publicdata/dto/managecost/privateuse/HeatCost.java
  src/main/java/bjs/zangbu/publicdata/service/managecost/Service.java
  src/main/java/bjs/zangbu/publicdata/service/managecost/privateuse/ManageCostService.java
  src/main/java/bjs/zangbu/publicdata/service/managecost/privateuse/ManageCostServiceImpl.java
Labels: ⭐ feat, 🍾영오

#158 feat: 공공데이터 api 추가 - 국토교통부_공동주택관리비(공용관리비)정보제공서비스
  src/main/java/bjs/zangbu/publicdata/controller/managecost/publicuse/PublicUseController.java
  src/main/java/bjs/zangbu/publicdata/dto/managecost/publicuse/CleanCost.java
  src/main/java/bjs/zangbu/publicdata/dto/managecost/publicuse/EduCost.java
  src/main/java/bjs/zangbu/publicdata/dto/managecost/publicuse/EtcCost.java
  src/main/java/bjs/zangbu/publicdata/dto/managecost/publicuse/VehicleCost.java
  src/main/java/bjs/zangbu/publicdata/service/managecost/publicuse/PublicUseService.java
  src/main/java/bjs/zangbu/publicdata/service/managecost/publicuse/PublicUseServiceImpl.java
Labels: ⭐ feat, 🍾영오

#160 docs: Deal 관련 swagger 및 javadoc 추가
  src/main/java/bjs/zangbu/deal/controller/DealController.java
  src/main/java/bjs/zangbu/deal/dto/request/DealRequest.java
  src/main/java/bjs/zangbu/deal/dto/response/DealResponse.java
  src/main/java/bjs/zangbu/deal/dto/response/DealWaitingListResponse.java
  src/main/java/bjs/zangbu/deal/vo/DealEnum.java
  src/main/java/bjs/zangbu/documentReport/dto/request/DocumentReportRequest.java
  src/main/java/bjs/zangbu/documentReport/dto/response/DocumentReportResponse.java
  src/test/java/bjs/zangbu/deal/controller/DealControllerTest.java
  src/test/java/bjs/zangbu/deal/mapper/DealMapperTest.java
  src/test/java/bjs/zangbu/deal/vo/DealTest.java
Labels: 📃 docs, 🐱해인

#168 feat: chat 수정
  src/main/java/bjs/zangbu/chat/controller/ChatController.java
  src/main/java/bjs/zangbu/chat/controller/ChatStompController.java
  src/main/java/bjs/zangbu/chat/dto/request/ChatRequest.java
  src/main/java/bjs/zangbu/chat/mapper/ChatMapper.java
  src/main/java/bjs/zangbu/chat/service/ChatService.java
  src/main/java/bjs/zangbu/chat/service/ChatServiceImpl.java
  src/test/java/bjs/zangbu/chat/mapper/ChatMapperTest.java
Labels: ♻️ refactor, 🎸수연

#170 docs: member, auth swagger 추가
  src/main/java/bjs/zangbu/member/controller/MemberController.java
  src/main/java/bjs/zangbu/member/dto/request/MemberRequest.java
  src/main/java/bjs/zangbu/member/dto/response/MemberResponse.java
  src/main/java/bjs/zangbu/security/account/controller/AuthController.java
  src/main/java/bjs/zangbu/security/account/dto/request/AuthRequest.java
  src/main/java/bjs/zangbu/security/account/dto/response/AuthResponse.java
  src/main/java/bjs/zangbu/security/account/service/AuthServiceImpl.java
  src/main/java/bjs/zangbu/security/util/JwtProcessor.java
Labels: ♻️ refactor, 📃 docs, 🐳 소정

#172 refactor: request 수정 및 service 수정
  src/main/java/bjs/zangbu/building/dto/request/BuildingRequest.java
  src/main/java/bjs/zangbu/building/service/MainService.java
  src/main/java/bjs/zangbu/building/service/MainServiceImpl.java
  src/main/java/bjs/zangbu/global/config/WebConfig.java
Labels: ♻️ refactor, 🐯 현빈

#174 refactor: security config에 cors 처리 추가
  src/main/java/bjs/zangbu/security/config/SecurityConfig.java
Labels: ♻️ refactor, 🐳 소정

#181 feat: docker file 및 docker compose 생성
  docker/docker-compose.yml
  docker/nginx/dockerfile
  docker/nginx/nginx.conf
  docker/tomcat/dockerfile
Labels: ⭐ feat, 🐯 현빈
